--use database rova;
insert into ACCOUNT(INITIAL_BALANCE,ACCOUNT_NUMBER) VALUES(400.0, 12345);

insert into CUSTOMER(CUSTOMER_ID, ACCOUNT_ID, FIRST_NAME, SURNAME, BALANCE)
values( 54321, 1,'John','Doe', 50.0);




