CREATE TABLE ACCOUNT(ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
                      INITIAL_BALANCE DECIMAL,
                      ACCOUNT_TYPE VARCHAR(100) NOT NULL DEFAULT 'DEFAULT_ACCOUNT',
                      CREATION_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                     );

CREATE TABLE CUSTOMER( ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
                                ACCOUNT_ID INTEGER NOT NULL,
                                CUSTOMER_ID INTEGER NOT NULL UNIQUE,
                                FIRST_NAME VARCHAR(250) NOT NULL,
                                SURNAME VARCHAR(250), BALANCE DECIMAL,
                                LAST_MODIFIED_DATE DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                FOREIGN KEY(ACCOUNT_ID) REFERENCES ACCOUNT(ID));

CREATE TABLE TRANSACTION(
ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ACCOUNT_ID INTEGER NOT NULL,
AMOUNT DECIMAL NOT NULL,
FOREIGN KEY(ACCOUNT_ID) REFERENCES ACCOUNT(ID)
);


