CREATE TABLE CUSTOMER_ACCOUNT( ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
                                CUSTOMER_ID INTEGER NOT NULL,
                                FIRST_NAME VARCHAR(250) NOT NULL,
                                SURNAME VARCHAR(250), BALANCE DECIMAL,
                                DATE_MODIFIED_DATE DATE NOT NULL DEFAULT CURRENT_DATE);
